import "@/styles/globals.scss"

import { clsx } from "clsx"
import { Analytics } from "@vercel/analytics/react"

import { iranSansExtraFont } from "@/lib/fonts"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={clsx("dark", iranSansExtraFont.className)}>
      <body>{children}</body>
      <Analytics />
    </html>
  )
}
